[workspace]
members = ["crates/kil-core", "crates/kil-cli"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2024"
license = "MIT"
rust-version = "1.90"
repository = "https://github.com/mkroplewski/kil"
homepage = "https://github.com/mkroplewski/kil"

[workspace.dependencies]
anyhow = "1.0.100"
clap = { version = "4.6.6", features = ["derive"] }
indexmap = { version = "2.11.4", features = ["serde"] }
kiutils_kicad = "0.3.0"
kiutils_sexpr = "0.1.1"
schemars = { version = "1.2.2", features = ["indexmap2", "uuid1"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
tempfile = "3.23.0"
thiserror = "2.0.17"
uuid = { version = "1.18.1", features = ["v5", "serde"] }
